version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@uifabric/react-cards"
    versions:
    - 0.115.10
    - 0.115.11
    - 0.115.12
    - 0.115.13
    - 0.115.14
    - 0.115.15
    - 0.115.18
    - 0.115.19
    - 0.115.21
    - 0.115.22
    - 0.115.23
    - 0.115.24
    - 0.115.25
    - 0.115.26
    - 0.115.27
    - 0.115.29
    - 0.115.30
    - 0.115.31
    - 0.115.32
    - 0.115.34
    - 0.115.35
    - 0.115.36
    - 0.115.37
    - 0.115.38
    - 0.115.39
    - 0.115.40
    - 0.115.41
    - 0.115.44
    - 0.115.45
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@fluentui/react"
    versions:
    - 8.0.0-beta.44
    - 8.0.0-beta.45
    - 8.0.0-beta.46
    - 8.0.0-beta.48
    - 8.0.0-beta.49
    - 8.0.0-beta.50
    - 8.0.0-beta.51
    - 8.0.0-beta.55
    - 8.0.0-beta.56
    - 8.0.0-beta.59
    - 8.0.0-beta.61
    - 8.1.0
    - 8.1.1
    - 8.1.4
    - 8.1.6
    - 8.1.7
    - 8.1.8
    - 8.10.1
    - 8.11.1
    - 8.11.2
    - 8.12.0
    - 8.12.1
    - 8.13.0
    - 8.2.0
    - 8.3.0
    - 8.3.1
    - 8.3.2
    - 8.4.0
    - 8.5.0
    - 8.5.1
    - 8.6.0
    - 8.6.1
    - 8.7.0
    - 8.7.1
    - 8.8.0
    - 8.9.0
    - 8.9.1
    - 8.9.2
    - 8.9.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
    - 4.2.3
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
