trigger:
- master

pool:
  vmImage: 'windows-2022'

stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build Vue Component
        variables:
          componentDirectory: '$(Build.SourcesDirectory)'
        steps:
        - task: Cache@2
          inputs:
            key: '"node_modules" | "$(Agent.OS)" | yarn.lock'
            restoreKeys: |
              "node_modules" | "$(Agent.OS)"
              "node_modules"
            path: '$(componentDirectory)/node_modules'
          displayName: Cache packages
        - task: CmdLine@2
          displayName: 'yarn install'
          inputs:
            script: 'yarn --frozen-lockfile'
            workingDirectory: '$(componentDirectory)'
        - task: CmdLine@2
          displayName: 'yarn build'
          inputs:
            script: 'yarn run build'
            workingDirectory: '$(componentDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(componentDirectory)/dist'
            ArtifactName: 'UIBuild'
            publishLocation: 'Container'
