# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2022'

stages:
  - stage: Build
    jobs:
      - job:
        displayName: Build Vue Component
        variables:
          componentDirectory: '$(Build.SourcesDirectory)/MenuUI'
          YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn
        steps:
        - task: Cache@2
          inputs:
            key: 'yarn | "$(Agent.OS)" | **/MenuUI/yarn.lock'
            restoreKeys: |
                yarn | "$(Agent.OS)"
                yarn
            path: $(YARN_CACHE_FOLDER)
          displayName: Cache Yarn packages
        - task: CmdLine@2
          displayName: 'yarn install'
          inputs:
            script: 'yarn --frozen-lockfile'
            workingDirectory: '$(componentDirectory)'
        - task: CmdLine@2
          displayName: 'yarn build'
          inputs:
            script: 'yarn run build'
            workingDirectory: '$(componentDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(componentDirectory)/dist'
            ArtifactName: 'UIBuild'
            publishLocation: 'Container'
