openapi: 3.0.1
info:
  title: MenuApi
  version: '1.0'
paths:
  /api/ingredient:
    get:
      tags:
        - Ingredients
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
  /api/recipe:
    get:
      tags:
        - Recipes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Recipe'
    post:
      tags:
        - Recipes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRecipe'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullRecipe'
  '/api/recipe/{recipeId}':
    get:
      tags:
        - Recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullRecipe'
    put:
      tags:
        - Recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewRecipe'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullRecipe'
  '/api/recipe/{recipeId}/ingredient':
    get:
      tags:
        - Recipes
      parameters:
        - name: recipeId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeIngredient'
components:
  schemas:
    FullRecipe:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/RecipeIngredient'
      additionalProperties: false
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        units:
          type: array
          items:
            $ref: '#/components/schemas/IngredientUnit'
      additionalProperties: false
    IngredientUnit:
      type: object
      properties:
        name:
          type: string
        abbreviation:
          type: string
      additionalProperties: false
    NewRecipe:
      type: object
      properties:
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/RecipeIngredient'
        name:
          type: string
      additionalProperties: false
    Recipe:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      additionalProperties: false
    RecipeIngredient:
      type: object
      properties:
        name:
          type: string
        unit:
          type: string
        amount:
          type: number
          format: double
      additionalProperties: false